### PR TITLE
examples: add unistd.h include for ssize_t

### PR DESCRIPTION
**Pull request by mdebski**
This failed to compile on my machine due to the lack of this header.

### CODE REVIEW

**Comment by eigenmatt** [comment]
Thanks, could you tell me what type of system you were trying to compile on?

**Comment by mdebski** [comment]
It was centos 7, but as a part of a custom build system, so probably quite different from the default setup.

Surprisingly I couldn't find a man page for ssize_t, so it is not fully clear what the canonical header for it should be, but these give some hints:
http://man7.org/linux/man-pages/man0/unistd.h.0p.html
https://linux.die.net/man/2/read

**Comment by mdebski** [comment]
ping?

**Comment by eigenmatt** [comment]
Yes it's not well defined which header should be included, I agree that unistd.h is the safest.  ssize_t is used in exanic/fifo_rx.h and exanic/config.h so really the include should be in those headers or in exanic/exanic.h.  We'll have a fix in the next release.

**Comment by eigenmatt** [comment]
unistd.h is added in the latest release (2.3.0)

**Pull request closed without merging**
